routes/web.php
<?php
Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('pendaftaran/data/kependudukan','FrontController@pendaftaran_pemohon_user')->name('pendaftaran.pemohon');
// is_pemohon
Route::prefix('pemohon')->name('pemohon.')->middleware('is_pemohon')->group(function() {
	// dashboard pemohon
	Route::get('home','HomeController@pemohonHome')->name('home');
	// edit pemohon jika belum punya detail
	Route::post('dashboard/post','HomeController@pemohondashboardpost')->name('home.dashboard.pemohon.post');
	// edit pemohon jika sudah punya detail
	Route::patch('dashboard/{id}/update/{user_id}','HomeController@pemohondashboardupdate')->name('home.dashboard.pemohon.update');
	// halaman perizinan
	Route::get('izin/{slug}','PemohonPerijinanController@izin')->name('perijinan');
	// post perizinan
	Route::post('izin/{slug}/post','PemohonPerijinanController@izinpost')->name('perijinan.post');
	// data ajax kecamatan
	Route::get('ajax_kecamatanid','PemohonPerijinanController@ajaxkecamatanid');
	//update status perijinan
	Route::patch('izin/{slug}/update_status/{id}','PemohonPerijinanController@update_status')->name('perijinan.update_status');
	// detail perizinan
	Route::get('izin/{slug}/detail/{id}','PemohonPerijinanController@detail')->name('perijinan.detail');
	// upload data
	Route::patch('izin/{slug}/update/{id}/upload_perizinan','PemohonPerijinanController@upload_perizinan')->name('perijinan.upload_perizinan');
	Route::delete('izin/{slug}/delete/{id}','PemohonPerijinanController@deleteperijinan')->name('perijinan.deleteperijinan');
	// crud data pemohon only index dan store
	Route::resource('pemohon','PemohonController')->only(['index','store']);
});

// bag_pemeriksaan
Route::get('bagian-pemeriksa/home','HomeController@bagPemeriksaHome')->name('bagPemeriksa.home')->middleware('is_bagpemeriksa');

// is_front_office
Route::prefix('front-office')->name('frontOffice.')->middleware('is_frontoffice')->group(function() {
	// homepage frontoffice
	Route::get('home','HomeController@frontOfficeHome')->name('home');
	// edit pemohon jika belum punya detail
	Route::post('dashboard/post','HomeController@fodashboardpost')->name('home.dashboard.fo.post');
	// edit pemohon jika sudah punya detail
	Route::patch('dashboard/{id}/update/{user_id}','HomeController@fodashboardupdate')->name('home.dashboard.fo.update');
	// crud data pemohon only index dan store
	Route::get('pemohon','PemohonController@foindex')->name('pemohon.foindex');
	Route::post('pemohon/post','PemohonController@fostore')->name('pemohon.fostore');
	// halaman perizinan
	Route::get('izin/{slug}','FoPerijinanController@izin')->name('perijinan');
	// post perizinan
	Route::post('izin/{slug}/post','FoPerijinanController@izinpost')->name('perijinan.post');
	// data ajax kecamatan
	Route::get('ajax_kecamatanid','FoPerijinanController@ajaxkecamatanid');
	//update status perijinan
	Route::patch('izin/{slug}/update_status/{id}','FoPerijinanController@update_status')->name('perijinan.update_status');
	// detail perizinan
	Route::get('izin/{slug}/detail/{id}','FoPerijinanController@detail')->name('perijinan.detail');
	// upload data
	Route::patch('izin/{slug}/update/{id}/upload_perizinan','FoPerijinanController@upload_perizinan')->name('perijinan.upload_perizinan');
	Route::delete('izin/{slug}/delete/{id}','FoPerijinanController@deleteperijinan')->name('perijinan.deleteperijinan');
});

app/Models/Pemohon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pemohon extends Model
{
	protected $table 	= 'pemohons';
	protected $fillable = ['kode_pemohon','registered_id','registered_name','user_id','nik','nama_lengkap','pekerjaan','jenis_kelamin','tempat_lahir','tanggal_lahir','rt','rw','alamat','npwp','no_telp'];

	public function user()
	{
		return $this->belongsTo('App\User');
	}
}

app/Http/Controllers/PemohonController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Pemohon;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class PemohonController extends Controller
{
	public function index()
	{
		$page		= 'Pendaftaran Pemohon';
		$pemohons	= Pemohon::orderBy('id','desc')->where('registered_id','=',auth()->user()->id)->get();
		// dd($pemohons);
		return view('pemohon.pemohons.index', compact('page','pemohons'));
	}

	public function store(Request $request)
	{
		// start cek foto profil 
		if($request->hasFile('foto_profil')){
			$foto_profil	= $request->foto_profil;
			$fotoProfilName	= time().'_'.Str::slug($request->nama_lengkap,'_').'.'.$foto_profil->getClientOriginalExtension();
			$foto_profil->move(public_path('img/user_profile'), $fotoProfilName);
		}else
		{
			$fotoProfilName = 'user_default.png';
		}
		// end cek foto profil 
		$lastpemohonid 			= Pemohon::orderBy('id','desc')->first();
		$generate_id 			= 'PMHN-'.date("dmYHi").$lastpemohonid->id;
		// dd($generate_id);
		$user						= new User;
		$user->name					= $request->nama_lengkap;
		$user->email				= $request->email;
		$user->email_verified_at	= now();
		$user->remember_token		= Str::random(15);
		$user->password				= Hash::make($request->password);
		$user->is_pemohon			= '1';
		$user->foto_profil			= $fotoProfilName;
		$user->save();
		$user_id				= $user->id;
		// pemohon
		$pemohon					= new Pemohon;
		$pemohon->kode_pemohon		= $generate_id;
		$pemohon->registered_id		= auth()->user()->id;
		$pemohon->registered_name	= auth()->user()->name;
		$pemohon->user_id			= $user->id;
		$pemohon->nik				= $request->nik;
		$pemohon->nama_lengkap		= $request->nama_lengkap;
		$pemohon->pekerjaan			= $request->pekerjaan;
		$pemohon->jenis_kelamin		= $request->jenis_kelamin;
		$pemohon->tempat_lahir		= $request->tempat_lahir;
		$pemohon->tanggal_lahir		= $request->tanggal_lahir;
		$pemohon->rt				= $request->rt;
		$pemohon->rw				= $request->rw;
		$pemohon->alamat			= $request->alamat;
		$pemohon->npwp				= $request->npwp;
		$pemohon->no_telp			= $request->no_telp;
		$pemohon->save();

		return redirect()->back()->with('message','Pendaftaran Pemohon Berhasil.');
	}

	public function foindex()
	{
		$page		= 'Pendaftaran Pemohon';
		$pemohons	= Pemohon::orderBy('id','desc')->where('registered_id','=',auth()->user()->id)->get();
		// dd($pemohons);
		return view('front_office.pemohons.index', compact('page','pemohons'));
	}
	public function fostore(Request $request)
	{
		// start cek foto profil 
		if($request->hasFile('foto_profil')){
			$foto_profil	= $request->foto_profil;
			$fotoProfilName	= time().'_'.Str::slug($request->nama_lengkap,'_').'.'.$foto_profil->getClientOriginalExtension();
			$foto_profil->move(public_path('img/user_profile'), $fotoProfilName);
		}else
		{
			$fotoProfilName = 'user_default.png';
		}
		// end cek foto profil 
		$lastpemohonid 			= Pemohon::orderBy('id','desc')->first();
		$generate_id 			= 'PMHN-'.date("dmYHi").$lastpemohonid->id;
		// dd($generate_id);
		$user						= new User;
		$user->name					= $request->nama_lengkap;
		$user->email				= $request->email;
		$user->email_verified_at	= now();
		$user->remember_token		= Str::random(15);
		$user->password				= Hash::make($request->password);
		$user->is_pemohon			= '1';
		$user->foto_profil			= $fotoProfilName;
		$user->save();
		$user_id				= $user->id;
		// pemohon
		$pemohon					= new Pemohon;
		$pemohon->kode_pemohon		= $generate_id;
		$pemohon->registered_id		= auth()->user()->id;
		$pemohon->registered_name	= auth()->user()->name;
		$pemohon->user_id			= $user->id;
		$pemohon->nik				= $request->nik;
		$pemohon->nama_lengkap		= $request->nama_lengkap;
		$pemohon->pekerjaan			= $request->pekerjaan;
		$pemohon->jenis_kelamin		= $request->jenis_kelamin;
		$pemohon->tempat_lahir		= $request->tempat_lahir;
		$pemohon->tanggal_lahir		= $request->tanggal_lahir;
		$pemohon->rt				= $request->rt;
		$pemohon->rw				= $request->rw;
		$pemohon->alamat			= $request->alamat;
		$pemohon->npwp				= $request->npwp;
		$pemohon->no_telp			= $request->no_telp;
		$pemohon->save();

		return redirect()->back()->with('message','Pendaftaran Pemohon Berhasil.');
	}
}

resources/views/pemohon/pendidikan/detail.blade.php
@extends('layouts.app')

@section('title')
{{ $ijin_pendidikan->kode_pendaftaran }} | {{ $perijinan->nama_perijinan }}
@endsection

@section('content')
<div class="app-title">
	<div>
		<h1><i class="fa fa-dashboard"></i> Detail {{ $perijinan->nama_perijinan }}</h1>
	</div>
	<ul class="app-breadcrumb breadcrumb">
		<li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
		<li class="breadcrumb-item"><a href="#">{{ $perijinan->singkatan_perijinan }}</a></li>
	</ul>
</div>
<div class="row">
	<div class="col-md-12">
		@if(session()->has('message'))
		<div class="bs-component">
			<div class="alert alert-dismissible alert-success">
				<button class="close" type="button" data-dismiss="alert">×</button><strong>{{ session()->get('message') }}</strong>
			</div>
		</div>
		@endif
		<div class="tile">
			<section class="invoice">
				<div class="row mb-4">
					<div class="col-6">
						<h2 class="page-header"><i class="fa fa-bell"></i> {{ $ijin_pendidikan->kode_pendaftaran }} | {{ $ijin_pendidikan->jenisijin->nama_jenisijin }}</h2>
					</div>
					<div class="col-6">
						<h5 class="text-right">Tanggal Daftar: {{ $ijin_pendidikan->tanggal_daftar }}</h5>
					</div>
				</div>
				<div class="row invoice-info">
					<div class="col-6">
						<strong>Status Ijin :</strong>{{ $ijin_pendidikan->datastatus->nama_status }}<br>
						@if($ijin_pendidikan->pemohon_id == 0)
						<strong>NIK :</strong>-<br>
						<strong>Nama Lengkap :</strong>-<br>
						<strong>Pekerjaan :</strong>-<br>
						<strong>Jenis Kelamin :</strong>-<br>
						<strong>Tempat/Tanggal Lahir :</strong>-<br>
						<strong>RT/RW :</strong>-<br>
						<strong>Alamat :</strong>-<br>
						<strong>NPWP :</strong>-<br>
						<strong>No.Telp :</strong>-<br>
						@else
						<strong>NIK :</strong> {{ $ijin_pendidikan->pemohon->nik }} <br>
						<strong>Nama Lengkap :</strong> {{ ucwords($ijin_pendidikan->pemohon->nama_lengkap) }} <br>
						<strong>Pekerjaan :</strong> {{ ucwords($ijin_pendidikan->pemohon->pekerjaan) }} <br>
						<strong>Jenis Kelamin :</strong> {{ $ijin_pendidikan->pemohon->jenis_kelamin }} <br>
						<strong>Tempat/Tanggal Lahir :</strong> {{ ucwords($ijin_pendidikan->pemohon->tempat_lahir) }}/{{ $ijin_pendidikan->pemohon->tanggal_lahir }} <br>
						<strong>RT/RW :</strong> {{ $ijin_pendidikan->pemohon->rt }}/{{ $ijin_pendidikan->pemohon->rw }} <br>
						<strong>Alamat :</strong> {{ ucwords($ijin_pendidikan->pemohon->alamat) }} <br>
						<strong>NPWP :</strong> {{ $ijin_pendidikan->pemohon->npwp }} <br>
						<strong>No.Telp :</strong> {{ $ijin_pendidikan->pemohon->no_telp }} <br>
						@endif
					</div>

					<div class="col-6">
						@if($ijin_pendidikan->jenis_izin == 2222)
							<strong>Alamat Sekolah :</strong>{{ $ijin_pendidikan->alamat_sekolah }}<br>
							<strong>Nomor Statistik Sekolah(NSS) :</strong>{{ $ijin_pendidikan->nss }}<br>
							<strong>Nomor Pokok Sekolah Nasional(NPSN) :</strong>{{ $ijin_pendidikan->npsn }}<br>
							<strong>Status Sekolah (Hasil Akreditasi) :</strong>{{ $ijin_pendidikan->status_sekolah }}<br>
							<strong>Penanggungjawab :</strong>{{ $ijin_pendidikan->penanggungjawab }}<br>
							<strong>Tanggal dan Nomor Akte Lembaga :</strong>{{ $ijin_pendidikan->tgl_no_akte }}<br>
							<strong>NIB :</strong>{{ $ijin_pendidikan->nib }}<br>
							<strong>Tanggal NIB :</strong>{{ $ijin_pendidikan->tgl_nib }}<br>
							<strong>Nama KBLI :</strong>{{ $ijin_pendidikan->nama_kbli }}<br>
						@elseif($ijin_pendidikan->jenis_izin == 2223)
							<strong>Alamat Sekolah :</strong>{{ $ijin_pendidikan->alamat_sekolah }}<br>
							<strong>Kepala Sekolah :</strong>{{ $ijin_pendidikan->kepala_sekolah }}<br>
							<strong>Nama Yayasan :</strong>{{ $ijin_pendidikan->nama_yayasan }}<br>
							<strong>NIB :</strong>{{ $ijin_pendidikan->nib }}<br>
							<strong>Tanggal NIB :</strong>{{ $ijin_pendidikan->tgl_nib }}<br>
						@else
						@endif
					</div>
				</div>
				@if($ijin_pendidikan->jenis_izin == 2222)
				<div class="row">
					<div class="col-12 table-responsive">
					  <table class="table table-striped">
						<thead>
						  <tr>
							<th>Syarat Izin</th>
							<th>Lihat</th>
							<th>Aksi</th>
						  </tr>
						</thead>
						<tbody>
							<tr>
								<td>Foto direktur berwarna 4x6 (2 lembar)</td>
								@if(is_null($ijin_pendidikan->foto_direktur))
								<td>-</td>
								@else
								<td>@include('pemohon.pendidikan.part.detail_foto_direktur')</td>
								@endif
								<td>@include('pemohon.pendidikan.part.upload_foto_direktur')</td>
							</tr>
							<tr>
								<td>Denah lokasi dan bangunan dengan situasi sekitar</td>
								@if(is_null($ijin_pendidikan->denah_lokasi))
								<td>-</td>
								@else
								<td>@include('pemohon.pendidikan.part.detail_denah_lokasi')</td>
								@endif
								<td>@include('pemohon.pendidikan.part.upload_denah_lokasi')</td>
							</tr>
							<tr>
								<td>Alamat dan denah lokasi tempat usaha</td>
								@if(is_null($ijin_pendidikan->alamat_lokasi))
								<td>-</td>
								@else
								<td>@include('pemohon.pendidikan.part.detail_alamat_lokasi')</td>
								@endif
								<td>@include('pemohon.pendidikan.part.upload_alamat_lokasi')</td>
							</tr>
							<tr>
								<td>Akta sewa menyewa, kontrak atau akte hak milik dari bangunan</td>
								@if(is_null($ijin_pendidikan->akta_sewa))
								<td>-</td>
								@else
								<td>@include('pemohon.pendidikan.part.detail_akta_sewa')</td>
								@endif
								<td>@include('pemohon.pendidikan.part.upload_akta_sewa')</td>
							</tr>
						</tbody>
					  </table>
					</div>
				</div>
				@else
				@endif
			</section>
		</div>
	</div>
</div>
@endsection

resources/views/pemohon/pendidikan/index.blade.php
@extends('layouts.app')
@section('title')
{{ $perijinan->nama_perijinan }} - {{ $perijinan->singkatan_perijinan }}
@endsection
@section('content')
<div class="app-title">
	<div>
		<h1><i class="fa fa-dashboard"></i> {{ $perijinan->nama_perijinan }}</h1>
	</div>
	<ul class="app-breadcrumb breadcrumb">
		<li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
		<li class="breadcrumb-item"><a href="#">{{ $perijinan->singkatan_perijinan }}</a></li>
	</ul>
</div>
<div class="row">
	<div class="col-md-12">
		@if(session()->has('message'))
		<div class="bs-component">
			<div class="alert alert-dismissible alert-success">
				<button class="close" type="button" data-dismiss="alert">×</button><strong>{{ session()->get('message') }}</strong>
			</div>
		</div>
		@endif
		<div class="tile">
			<div class="tile-body">
				<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#tambahIjinPendidikan" aria-expanded="false" aria-controls="tambahIjinPendidikan">
					Tambah
				</button>
			</div>
		</div>
		<div class="collapse" id="tambahIjinPendidikan">
			<div class="card card-body">
				{{ Form::open(['route'=>['pemohon.perijinan.post',$perijinan->slug_perijinan],'method'=>'POST','files'=>true]) }}
				@include('pemohon.pendidikan.tambah_data_ijin')
				{{ Form::close() }}
			</div>
		</div>
		<div class="tile">
			<div class="tile-body">
				<table class="table table-bordered ijin_pendidikan">
					<thead>
						<tr>
							<th>No</th>
							<th>Tanggal Daftar</th>
							<th>Jenis Izin</th>
							<th>NIK</th>
							<th>Nama Lengkap</th>
							<th>Status Pemohon</th>
							<th>Detail</th>
							<th>Ubah Status</th>
							<th width="100px">Aksi</th>
						</tr>
					</thead>
					<tbody>
						@foreach($dataIjinPendidikan as $dip)
						<tr>
							<td>{{ $loop->iteration }}</td>
							<td>{{ $dip->tanggal_daftar }}</td>
							<td>{{ $dip->jenisijin->nama_jenisijin }}</td>
							@if($dip->pemohon_id == 0)
							<td>-</td>
							<td>-</td>
							@else
							<td>{{ $dip->pemohon->nik }}</td>
							<td>{{ $dip->pemohon->nama_lengkap }}</td>
							@endif
							<td>{{ $dip->datastatus->nama_status }}</td>
							<td>
								<a href="{{ route('pemohon.perijinan.detail',[$perijinan->slug_perijinan,$dip->id]) }}" class="btn btn-block btn-primary"><i class="fa fa-info-circle" aria-hidden="true"></i></a>
							</td>
							@include('pemohon.pendidikan.ubah_status')
							<td>
								{{ Form::model($dip, ['route'=>['pemohon.perijinan.deleteperijinan', $perijinan->slug_perijinan,$dip->id],'method'=>'POST']) }}
									@method('DELETE')
									<button type="submit" onclick="return confirm('Yakin mau hapus data ini ?');" class="btn btn-block btn-danger"><i class="fa fa-trash" aria-hidden="true"></i></button>
								{{ Form::close() }}
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
@endsection

@push('styles')
<link rel="stylesheet" href="{{ asset('css/9oExJP7cAB_ts.css') }}">
<link href="{{ asset('css/8mCcq93x7C_s2.css') }}" rel="stylesheet" />
<link rel="stylesheet" href="{{ asset('css/JMtvK2onmA_fltpckr.css') }}">
<link rel="stylesheet" href="{{ asset('css/5EC8VBfS_dt.css') }}">
@endpush
@push('scripts')
<script src="{{ asset('js/5EC8VBfS_dt.js') }}"></script>
<script src="{{ asset('js/8mCcq93x7C_s2.js') }}"></script>
<script src="{{ asset('js/9oExJP7cAB_ts.js') }}"></script>
<script src="{{ asset('js/JMtvK2onmA_fltpckr.js') }}"></script>

<script>
	var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
	$(document).ready(function() {
		$('.ijin_pendidikan').DataTable({
			'order': [[0,'desc']],
		});
		$('#pemohon_id').select2({
			theme: "bootstrap",
			ajax: {
				url: "{{ route('pemohon.getdatapemohon') }}",
				type: 'post',
				delay: 250,
				dataType: 'json',
				data: function(params){
					return{
						_token: CSRF_TOKEN,
						search: params.term
					};
				},
				processResults: function(response){
					return{
						results: response
					};
				},
				cache: true
			}
		});
	});
	flatpickr(".tgl_nib",{
		altInput: true,
		altFormat: "F j, Y",
		dateFormat: "d-m-Y",
	});
	$('#kecamatan_id').change(function(e){
		console.log(e);
		var kab_id = e.target.value;
		$.get('/pemohon/ajax_kecamatanid?kab_id='+kab_id, function(data){
			console.log(data);
			$('#desa_group').show();
			$('#desa_id').empty();
			$.each(data, function(index, kabidObj){
				$('#desa_id').append('<option value="'+kabidObj.id+'">'+kabidObj.name+'</option>');
			});
		});
	});
	$('#jenis_izin').change(function(e){
		console.log(e.target.value);
		var izin_id = e.target.value;
		if(izin_id == 2222){
			$('#pilihsatu').show();
			$('#pilihdua').hide();
		}else if(izin_id == 2223){
			$('#pilihsatu').hide();
			$('#pilihdua').show();
		}else{
			$('#pilihsatu').hide();
			$('#pilihdua').hide();
		}
	});
	$('#pilih_pemohon').change(function(e){
		console.log(e.target.value);
		var pil_pemohon = e.target.value;
		if(pil_pemohon == 1){
			$('#pemohon1').show();
			$('#pemohon2').hide();
		}else if(pil_pemohon == 2){
			$('#pemohon1').hide();
			$('#pemohon2').show();
		}else{
			$('#pemohon1').hide();
			$('#pemohon2').hide();
		}
	});
	new TomSelect("#kecamatan_id",{
		create: false,
		sortField: {
			field: "text",
			direction: "asc"
		}
	});
	new TomSelect("#status_pemohon",{
		create: false,
		sortField: {
			field: "text",
			direction: "asc"
		}
	});
	$('#desa_id').select2({
		theme: "bootstrap"
	});
	$('#jenis_izin').select2({
		theme: "bootstrap"
	});
</script>
@endpush

resources/views/pemohon/pendidikan/ubah_status.blade.php
<td class="text-center">
	<button type="button" class="btn btn-warning" data-toggle="modal" data-target="#ubahstatus{{ $dip->id }}">
		<i class="fa fa-refresh" aria-hidden="true"></i>
	</button>
</td>

<div class="modal fade" id="ubahstatus{{ $dip->id }}" tabindex="-1" role="dialog" aria-labelledby="ubahstatus{{ $dip->id }}_Label" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="ubahstatus{{ $dip->id }}_Label">Ubah Status Pengajuan</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			{{ Form::model($dip, ['route'=>['pemohon.perijinan.update_status', $perijinan->slug_perijinan,$dip->id],'method'=>'POST']) }}
			@method('PATCH')
			<div class="modal-body">
				<div class="form-group">
					{{ Form::label('status_pemohon','Status Pemohon') }}
					{{ Form::select('status_pemohon',$status,$dip->status_id,['placeholder'=>'Pilih Status Pemohon','id'=>'status_pemohon','class'=>'form-control','required']) }}
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Update Status</button>
			</div>
			{{ Form::close() }}
		</div>
	</div>
</div>